### ISSUE TITLE
打开不开

### ISSUE THREAD

**Issue by yobdc957232834** [odomu/aliyunpan#1]
win11  25300.1000安装打不开什么情况

**Comment by prajna0** [comment]
Windows 10 1909 (OS18363.418)，一切正常

**Comment by 121592512** [comment]
25 23:37:36 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:37:36 : danger : aReloadDowned 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:37:36 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:37:36 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:37:36 : danger : aReloadDowning 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C._read (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:37:36 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C._read (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:37:35 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:37:35 : danger : UserDALLDB 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:37:35 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:37:35 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:37:35 : danger : ShareDALLDB 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C.get (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/ali...
25 23:37:35 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C.get (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/ali...
25 23:37:34 : success : 小白羊启动
25 23:36:09 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:36:09 : danger : unhandledrejection
25 23:36:09 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C.put (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/ali...
25 23:35:35 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:35:27 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:35:27 : danger : aReloadDowned 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:35:27 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:35:27 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:35:27 : danger : aReloadDowning 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C._read (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:35:27 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C._read (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:35:26 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:35:26 : danger : UserDALLDB 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:35:26 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:76467
    at executePromiseTask (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/a...
25 23:35:26 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:6227)
25 23:35:26 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/alixbyv3.10.24-x64/win-unpacked/resources/app.asar/dist/index.js:22:12139)
    at C.get (file:///D:/%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6/ali...
25 23:35:26 : success : 小白羊启动
