### ISSUE TITLE
无法下载，无法连接Aria

### ISSUE THREAD

**Issue by Mars-LLL** [odomu/aliyunpan#122]
### 问题描述 / Describe Bugs

无法启动Aria，下载提示Aria2c未知错误

### 复现步骤 / How to reproduce

![QQ截图20230528130010](https://github.com/odomu/aliyunpan/assets/108523199/6c189c46-5f07-42a6-a0e8-ebad988646e1)

### 日志提交 / Relevant log output

28 12:57:42 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:54148)
    at ue.onerror (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:61969)
28 12:57:42 : danger : Uncaught Error: Unhandled error. (undefined)
28 12:57:42 : danger : onerror
28 12:57:40 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:54148)
    at ue.onerror (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:61969)
28 12:57:40 : danger : Uncaught Error: Unhandled error. (undefined)
28 12:57:38 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:54148)
    at ue.onerror (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:61969)
28 12:57:38 : danger : onerror
28 12:57:36 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:54148)
    at ue.onerror (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:61969)
28 12:57:36 : danger : Uncaught Error: Unhandled error. (undefined)
28 12:57:34 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:54148)
    at ue.onerror (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:61969)
28 12:57:34 : danger : onerror
28 12:57:32 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:54148)
    at ue.onerror (file:///H:/Aliyun/alixby/resources/app.asar/dist/index.js:76:61969)
28 12:57:32 : danger : Uncaught Error: Unhandled error. (undefined)
28 12:57:12 : success : 小白羊启动
28 12:54:11 : success : 小白羊启动
28 12:52:59 : success : 小白羊启动

### 软件版本 / App version

3.10.30

### 系统类型 / System type

Windows

**Comment by odomu** [comment]
安装路径不能有空格，否则aria2无法启动

**Comment by Mars-LLL** [comment]
安装路径H:\Aliyun\alixby\alixby.exe
