### ISSUE TITLE
新安装 aria报错

### ISSUE THREAD

**Issue by Yolocccc** [odomu/aliyunpan#137]
### 问题描述 / Describe Bugs

打开后一直在重新启动，用户能正常登录
![bab2f245f8217f668db0e25e60f606e](https://github.com/odomu/aliyunpan/assets/21006581/98a1065c-db4b-45a2-9c50-91de08244e57)

### 复现步骤 / How to reproduce

加管理员权限也一样循环

### 日志提交 / Relevant log output

31 09:16:10 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:16:10 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:16:10 : danger : onerror
31 09:16:08 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:16:08 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:16:08 : danger : onerror
31 09:16:06 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:16:06 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:16:06 : danger : onerror
31 09:16:04 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:16:04 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:16:04 : danger : onerror
31 09:16:02 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:16:02 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:16:02 : danger : onerror
31 09:16:00 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:16:00 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:16:00 : danger : onerror
31 09:15:42 : success : 小白羊启动
31 09:15:32 : success : 小白羊启动
31 09:13:43 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:13:43 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:13:41 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:13:41 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:13:39 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:13:39 : danger : onerror
31 09:13:37 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:13:35 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:13:35 : danger : onerror
31 09:13:33 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:54223)
    at ue.onerror (file:///F:/Program%20Files/alixby/resources/app.asar/dist/index.js:102:62044)
31 09:13:33 : danger : Uncaught Error: Unhandled error. (undefined)
31 09:13:15 : success : 小白羊启动

### 软件版本 / App version

v3.10.32

### 系统类型 / System type

Windows

**Comment by Yolocccc** [comment]
又仔细看了一下 program files中间也算个空格 那没事了
