### ISSUE TITLE
下载文件保存位置-默认使用此路径取消后报错，无法进行下载。

### ISSUE THREAD

**Issue by weakestan** [odomu/aliyunpan#17]
日志：
errorHandler //== Error ==// Cannot read properties of undefined (reading 'resetFields') //== Stack ===// TypeError: Cannot read properties of undefined (reading 'resetFields') at handleClose (file:///D:/tools/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E5%B0%8F%E7%99%BD%E7%BE%8A%E7%89%88/resources/app.asar/dist/index.js:186:27097) at callWithErrorHandling (file:///D:/tools/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E5%B0%8F%E7%99%BD%E7%BE%8A%E7%89%88/resources/app.asar/dist/index.js:1:17585) at callWithAsyncErrorHandling ...

**Comment by weakestan** [comment]
全新安装，重制后也是如此。
勾选后下载正常。
