### ISSUE TITLE
请求的版本（100）小于现有版本（140）。版本错误：请求的版本（1 00）比现有版本（140）旧。

### ISSUE THREAD

**Issue by tbbdxbb** [odomu/aliyunpan#229]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [ ] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

rejection VersionError The requested version (100) is less than the existing version (140). VersionError: The requested version (1 00) is les than the existing version (140).
![屏幕截图 2023-11-22 210513](https://github.com/odomu/aliyunpan/assets/106042780/2d5c701d-f6c4-44e4-985d-bb2b3639e74f)

### 复现步骤 / How to reproduce

安装完 https://github.com/gaozhangmin/aliyunpan XBYDriver-3.12.1-win-x64更新后出现此问题，之前正常使用。

### 日志提交(截取部分日志，不要太长) / 使用Ctrl+Shift+F12打开DevTools截图错误的网络请求

22 21:10:42 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 21:10:42 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 21:10:42 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 21:10:42 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 21:10:41 : success : 小白羊启动
22 21:04:56 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 21:04:56 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 21:04:56 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 21:04:56 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 21:04:55 : success : 小白羊启动
22 21:02:26 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 21:02:26 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 21:02:26 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 21:02:26 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 21:02:25 : success : 小白羊启动
22 21:00:55 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 21:00:55 : danger : unhandledrejection
22 21:00:25 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 21:00:25 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 21:00:25 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 21:00:25 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 21:00:24 : success : 小白羊启动
22 20:58:46 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 20:58:46 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 20:58:46 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 20:58:46 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 20:58:45 : success : 小白羊启动
22 20:58:25 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 20:58:25 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program...
22 20:58:25 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 20:58:25 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program%20Files/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:...
22 20:58:25 : danger : unhandledrejection
22 20:58:24 : success : 小白羊启动
22 20:41:32 : success : 小白羊启动
22 20:40:19 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 20:39:57 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 20:39:57 : danger : unhandledrejection
22 20:38:49 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 20:38:49 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 20:38:49 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 20:38:49 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 20:38:48 : success : 小白羊启动
22 20:37:27 : success : 小白羊启动
22 20:36:51 : danger : UserDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 20:36:51 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///D:/Program/alixby/...
22 20:36:51 : danger : ShareDALLDB 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 20:36:51 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (100) is less than the existing version (140).
 VersionError: The requested version (100) is less than the existing version (140).
    at tempTransaction (file:///D:/Program/alixby/resources/app.asar/dist/index.js:22:10120)
    at C._trans (file:///D:/Program...
22 20:36:50 : success : 小白羊启动
22 20:35:51 : success : 小白羊启动
22 20:31:40 : success : 小白羊启动
22 20:29:06 : success : 小白羊启动
17 22:35:37 : warning : _ApiDirFileListCount err=root 403
17 22:35:37 : warning : _ApiDirFileListCount err=root 403
17 22:35:37 : warning : ApiUserPic err=401
17 22:35:24 : success : 小白羊启动
17 22:33:09 : success : 小白羊启动

### 软件版本 / App version

3.23 82722

### 系统类型 / System type

Windows

### 系统版本 / System Version

10 22H2 19045.3693

**Comment by odomu** [comment]
升级到最新版本，因为他是fork我的代码二次开发
