### ISSUE TITLE
macOS m1 aria2有问题

### ISSUE THREAD

**Issue by killdayu** [odomu/aliyunpan#67]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/62084769/235440761-c9bed317-6339-444b-815c-932b8fa63859.png">

`01 18:27:23 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:23 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:27:23 : danger : onerror
01 18:27:23 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:23 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:27:23 : danger : onerror
01 18:27:18 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:18 : danger : onerror
01 18:27:18 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:18 : danger : onerror
01 18:27:14 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:14 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:27:11 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:11 : danger : onerror
01 18:27:07 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:07 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:27:02 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:02 : danger : onerror
01 18:27:02 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:27:02 : danger : onerror
01 18:26:58 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:58 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:54 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:54 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:48 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:48 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:48 : danger : onerror
01 18:26:42 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:42 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:37 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:37 : danger : onerror
01 18:26:33 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:33 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:31 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:31 : danger : onerror
01 18:26:29 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:21 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:21 : danger : onerror
01 18:26:20 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:18 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:18 : danger : onerror
01 18:26:17 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:17 : danger : onerror
01 18:26:14 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:14 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:11 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:11 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:11 : danger : onerror
01 18:26:11 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:11 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:05 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:05 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:26:05 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:02 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:26:02 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:25:56 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:56 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:56 : danger : onerror
01 18:25:51 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:51 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:25:45 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:45 : danger : onerror
01 18:25:45 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:45 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:25:42 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:42 : danger : onerror
01 18:25:41 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:34 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:34 : danger : onerror
01 18:25:30 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:30 : danger : onerror
01 18:25:30 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:30 : danger : onerror
01 18:25:23 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:23 : danger : onerror
01 18:25:19 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:19 : danger : onerror
01 18:25:19 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:19 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:25:16 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:16 : danger : onerror
01 18:25:11 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:11 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:25:11 : danger : onerror
01 18:25:07 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:07 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:25:06 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:06 : danger : onerror
01 18:25:05 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:05 : danger : Uncaught Error: Unhandled error. (undefined)
01 18:25:01 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:25:01 : danger : onerror
01 18:24:58 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:24:58 : danger : onerror
01 18:24:54 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:24:54 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:24:54 : danger : onerror
01 18:24:54 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ne.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:53097)
    at le.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60918)
01 18:24:54 : danger : Uncaught Error: Unhandled error. (undefined)
`

**Comment by killdayu** [comment]
错误信息:Command failed: /Applications/alixby.app/Contents/Resources/engine/aria2c --stop-with-process=33924 -D --conf-path=/Applications/alixby.app/Contents/Resources/engine/aria2.conf --rpc-listen-port=16800
/bin/sh: /Applications/alixby.app/Contents/Resources/engine/aria2c: Permission denied

**Comment by odomu** [comment]
Permission denied： 管理员权限

**Comment by skykain** [comment]
同macOS 报这个错，没办法，只好连接Motrix的aria2c服务使用，当然也可以自己命令行启动aria2c服务去连接，P.S.要设置[RPC 授权密钥]

**Comment by odomu** [comment]
@rosspsp 你这个是什么架构的

**Comment by rosspsp** [comment]
@odomu m1的

**Comment by skykain** [comment]
终端运行
`chmod +x /Applications/alixby.app/Contents/Resources/engine/aria2c`
触决问题
但意外之喜是发现连本地的Motrix的aria2c服务的话，下载速度竟然比软件自带的aria2c快了6倍

**Comment by rosspsp** [comment]
@odomu 最新版问题已解决
