### ISSUE TITLE
为什么我使用的时候一直报错？

### ISSUE THREAD

**Issue by Yamazaki-wu** [odomu/aliyunpan#8]
在线播放报错：
ApiFileDownloadUrl err=63f8bcab5559ef2533194b79b12b28ff52d48314 401

下载报错：
errorHandler //== Error ==// Cannot read properties of undefined (reading 'resetFields') //== Stack ===// TypeError: Cannot read properties of undefined (reading 'resetFields') at handleClose (file:///E:/%E5%B0%8F%E7%99%BD%E7%BE%8A-%E9%98%BF%E9%87%8C%E4%BA%91/resources/app.asar/dist/index.js:186:27097) at callWithErrorHandling (file:///E:/%E5%B0%8F%E7%99%BD%E7%BE%8A-%E9%98%BF%E9%87%8C%E4%BA%91/resources/app.asar/dist/index.js:1:17585) at callWithAsyncErrorHandling (file:///E:/%E5%B0%8F%E7%99%BD%E7%BE%8A-%E9%98...

原本安装了官方的客户端，会有影响么？但是后来卸载了官方版，依旧报错。

**Comment by lrs95** [comment]
清除全部数据，你卸载了原来的，但配置文件还在C盘下

**Comment by lrs95** [comment]
![image](https://user-images.githubusercontent.com/24587454/221306644-cc306f25-460e-47e3-9283-11365fbb1c05.png)

**Comment by shemengjia** [comment]
> ![image](https://user-images.githubusercontent.com/24587454/221306644-cc306f25-460e-47e3-9283-11365fbb1c05.png)



> 清除全部数据，你卸载了原来的，但配置文件还在C盘下
老哥，aira2本地连接已断开怎么解决啊

**Comment by lrs95** [comment]
> > ![image](https://user-images.githubusercontent.com/24587454/221306644-cc306f25-460e-47e3-9283-11365fbb1c05.png)
> 
> > 清除全部数据，你卸载了原来的，但配置文件还在C盘下
> > 老哥，aira2本地连接已断开怎么解决啊

试试以管理员方式运行

**Comment by Yamazaki-wu** [comment]
你说得方法都试过了，“删除全部数据”，打开软件用账号密码登录，内置播放器，无法播放，报错情况相同。
以管理员身份执行，操作步骤如上，内置播放器，无法播放。
是不是安装了官方客户端（与小白羊在同一个分区不同目录）的关系？

**Comment by lrs95** [comment]
> 你说得方法都试过了，“删除全部数据”，打开软件用账号密码登录，内置播放器，无法播放，报错情况相同。
> 
> 以管理员身份执行，操作步骤如上，内置播放器，无法播放。
> 
> 是不是安装了官方客户端（与小白羊在同一个分区不同目录）的关系？

不是让扫码登录吗？

**Comment by Yamazaki-wu** [comment]
> > 你说得方法都试过了，“删除全部数据”，打开软件用账号密码登录，内置播放器，无法播放，报错情况相同。
> > 以管理员身份执行，操作步骤如上，内置播放器，无法播放。
> > 是不是安装了官方客户端（与小白羊在同一个分区不同目录）的关系？
> 
> 不是让扫码登录吗？

扫码登录也一样啊，三种登录方式都试过的。
删除数据后重启客户端，关闭，管理员身份执行，扫码登录，无论内置还是外置potplay都没法播放。

**Comment by lrs95** [comment]
> > > 你说得方法都试过了，“删除全部数据”，打开软件用账号密码登录，内置播放器，无法播放，报错情况相同。
> > > 以管理员身份执行，操作步骤如上，内置播放器，无法播放。
> > > 是不是安装了官方客户端（与小白羊在同一个分区不同目录）的关系？
> > 
> > 
> > 不是让扫码登录吗？
> 
> 扫码登录也一样啊，三种登录方式都试过的。 删除数据后重启客户端，关闭，管理员身份执行，扫码登录，无论内置还是外置potplay都没法播放。

那就不清楚了，反正我看大多数人用的都没什么问题

**Comment by cattitom** [comment]
同样报错，下载和在线观看都是ApiFileDownloadUrl err=63d25b34ef7c5abef457419b91cc3d35ed8e8044 401

**Comment by Yamazaki-wu** [comment]
> 同样报错，下载和在线观看都是ApiFileDownloadUrl err=63d25b34ef7c5abef457419b91cc3d35ed8e8044 401

真不容易，还以为就我一人会这样。

**Comment by hjl618276** [comment]
W7也是同样报错，下载和在线观看都是ApiFileDownloadUrl err=63d25b34ef7c5abef457419b91cc3d35ed8e8044 401

**Comment by hjl618276** [comment]
难道和系统有关？

**Comment by hjl618276** [comment]
之前的小白羊是可以使用的

**Comment by odomu** [comment]
解析失败的需要去网页版把绑定设备减少，最多只能绑定10个设备
